# : Manager [[[

[manager]
cwd = { fg = "#d9e4eb" }

# Tab
tab_active = { fg = "#003546", bg = "#69d3ff", bold = true }
tab_inactive = { fg = "#bee9ff", bg = "#001f2a" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#7198ff", bg = "#7198ff" }
marker_cut = { fg = "#d7e2ff", bg = "#d7e2ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#afc7f8", bg = "#afc7f8" }

# Count
count_copied = { fg = "#001b3f", bg = "#d7e2ff" }
count_cut = { fg = "#001b3f", bg = "#d7e2ff" }
count_selected = { fg = "#003546", bg = "#afc7f8" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#69d3ff" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#003546", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#69d3ff", fg = "#003546", bold = true }
normal_alt  = { bg = "#3e484e", fg = "#bdc8cf" }

# Select mode
select_main = { bg = "#aec9e6", fg = "#163349", bold = true }
select_alt  = { bg = "#3e484e", fg = "#bdc8cf" }

# Unset mode
unset_main = { bg = "#afc7f8", fg = "#163059", bold = true }
unset_alt  = { bg = "#3e484e", fg = "#bdc8cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#69d3ff", bg = "#303b40" }
progress_error = { fg = "#ffb4ab", bg = "#303b40" }

# Permissions
permissions_t = { fg = "#3b7bc0" }
permissions_w = { fg = "#2265ec" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#3e73ff" }
permissions_s = { fg = "#25b5ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#69d3ff" }
active = { fg = "#afc7f8", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#69d3ff" }
value = { fg = "#d9e4eb" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#69d3ff", bg = "#003546" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#69d3ff" }
title = {}
hovered = { fg = "#d7e2ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#303b40" }
cand = { fg = "#69d3ff" }
rest = { fg = "#003546" }
desc = { fg = "#d9e4eb" }
separator = " ‚ñ∂ "
separator_style = { fg = "#d9e4eb" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#d9e4eb" }
run = { fg = "#d9e4eb" }
footer = { fg = "#163349", bg = "#aec9e6" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#afc7f8" }
title_warn = { fg = "#69d3ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#d9e4eb" },
    { name = "*/", fg = "#69d3ff" },
]

# : ]]]