# : Manager [[[

[mgr]
cwd = { fg = "#f7dce0" }

# Tab
tab_active = { fg = "#660029", bg = "#ffb1c1", bold = true }
tab_inactive = { fg = "#ffd9df", bg = "#3f0017" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff9068", bg = "#ff9068" }
marker_cut = { fg = "#ffdbce", bg = "#ffdbce" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#ffb598", bg = "#ffb598" }

# Count
count_copied = { fg = "#370e00", bg = "#ffdbce" }
count_cut = { fg = "#370e00", bg = "#ffdbce" }
count_selected = { fg = "#660029", bg = "#ffb598" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#ffb1c1" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#660029", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb1c1", fg = "#660029", bold = true }
normal_alt  = { bg = "#544245", fg = "#dac0c4" }

# Select mode
select_main = { bg = "#f5b7b1", fg = "#4c2522", bold = true }
select_alt  = { bg = "#544245", fg = "#dac0c4" }

# Unset mode
unset_main = { bg = "#ffb598", fg = "#52230d", bold = true }
unset_alt  = { bg = "#544245", fg = "#dac0c4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb1c1", bg = "#463538" }
progress_error = { fg = "#ffb4ab", bg = "#463538" }

# Permissions
permissions_t = { fg = "#e43a29" }
permissions_w = { fg = "#fe4800" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff6b35" }
permissions_s = { fg = "#ff405e" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb1c1" }
active = { fg = "#ffb598", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb1c1" }
value = { fg = "#f7dce0" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb1c1", bg = "#660029" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb1c1" }
title = {}
hovered = { fg = "#ffdbce", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#463538" }
cand = { fg = "#ffb1c1" }
rest = { fg = "#660029" }
desc = { fg = "#f7dce0" }
separator = " ‚ñ∂ "
separator_style = { fg = "#f7dce0" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f7dce0" }
run = { fg = "#f7dce0" }
footer = { fg = "#4c2522", bg = "#f5b7b1" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#ffb598" }
title_warn = { fg = "#ffb1c1" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f7dce0" },
    { name = "*/", fg = "#ffb1c1" },
]

# : ]]]