# : Manager [[[

[mgr]
cwd = { fg = "#e2e1ef" }

# Tab
tab_active = { fg = "#00169d", bg = "#bcc2ff", bold = true }
tab_inactive = { fg = "#dfe0ff", bg = "#000a64" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#c675ff", bg = "#c675ff" }
marker_cut = { fg = "#f0dbff", bg = "#f0dbff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d9bbf2", bg = "#d9bbf2" }

# Count
count_copied = { fg = "#27103c", bg = "#f0dbff" }
count_cut = { fg = "#27103c", bg = "#f0dbff" }
count_selected = { fg = "#00169d", bg = "#d9bbf2" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#bcc2ff" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#00169d", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#bcc2ff", fg = "#00169d", bold = true }
normal_alt  = { bg = "#454651", fg = "#c6c5d3" }

# Select mode
select_main = { bg = "#cbc1e9", fg = "#322c4c", bold = true }
select_alt  = { bg = "#454651", fg = "#c6c5d3" }

# Unset mode
unset_main = { bg = "#d9bbf2", fg = "#3d2653", bold = true }
unset_alt  = { bg = "#454651", fg = "#c6c5d3" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#bcc2ff", bg = "#383843" }
progress_error = { fg = "#ffb4ab", bg = "#383843" }

# Permissions
permissions_t = { fg = "#6c50c1" }
permissions_w = { fg = "#913bd9" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#b042ff" }
permissions_s = { fg = "#464cff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#bcc2ff" }
active = { fg = "#d9bbf2", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#bcc2ff" }
value = { fg = "#e2e1ef" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#bcc2ff", bg = "#00169d" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#bcc2ff" }
title = {}
hovered = { fg = "#f0dbff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#383843" }
cand = { fg = "#bcc2ff" }
rest = { fg = "#00169d" }
desc = { fg = "#e2e1ef" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e2e1ef" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e2e1ef" }
run = { fg = "#e2e1ef" }
footer = { fg = "#322c4c", bg = "#cbc1e9" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#d9bbf2" }
title_warn = { fg = "#bcc2ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e2e1ef" },
    { name = "*/", fg = "#bcc2ff" },
]

# : ]]]